voyager 1.0.1
Minecraft-Java-Edition-Speedrunning/legal-mods pull request #3
Opened 2023-12-10 00:41 UTC by tildejustin

take two

source: https://github.com/tildejustin/voyager/tree/abb9738ac777536846fad917199ee7b485cc19d0
changes the implementation from a [dastardly overwrite](https://github.com/tildejustin/voyager/blob/7bbe8a5bb29176a3bdd916b06c3f3d65c58bbb9b/src/main/java/me/modmuss50/voyager/mixin/StructureManagerMixin.java#L27-L49) to a [localized inject](https://github.com/tildejustin/voyager/blob/3240c3ce9fb95378a5c6e99424a08cd9710bb44a/src/main/java/me/modmuss50/voyager/mixin/StructureManagerMixin.java#L40-L46). this change has been battle-tested in fabric api and was just never released stand-alone. i also added a mixin config so as to avoid modifying any bytecode when java 10 or less was used, as the mod is unnecessary in that case.

2023-12-10 05:58 UTC, DuncanRuns requested changes
Please remove .gitignore

2023-12-10 05:58 UTC, DuncanRuns commented on .gitignore
this probably shouldn't be here

2023-12-10 19:54 UTC, DuncanRuns approved these changes
LGTM
Please wait for leaderboard moderator approval before merging

2023-12-17 13:22 UTC, tildejustin commented
note to self: change the inject method to `<init>*`

2023-12-23 23:54 UTC, tildejustin commented
commit: https://github.com/tildejustin/voyager/commit/78bcc4a494c018ff3170619932bbf7982ff4dc65
adds support for older versions

2024-01-15 23:43 UTC, DuncanRuns commented
I am not a big fan of that jar name

2024-01-16 01:03 UTC, tildejustin commented
new source: https://github.com/tildejustin/voyager/tree/v1.0.1

2024-01-16 01:06 UTC, DuncanRuns approved these changes

2024-02-11 19:53 UTC, merged